### ISSUE TITLE
Dataset Problems

### ISSUE THREAD

**Issue by aduaa** [HestiaSky/IMF-Pytorch#1]
Excuse me, would it be possible for you to share the dataset mentioned in the article? It would be of great help to me. Thank you very much for your assistance. If it's not too much trouble, could you please send it to my email at TianY_Du@163.com?

**Comment by CuteMing** [comment]
Please send me a copy if you can, thanks！ It would be of great help to me, too.  My email at wjhm0722@163.com

**Comment by ZeroerWiser** [comment]
Please send me a copy if you also can, thanks！ It would be of great help to me, too. My email at sihaohe@126.com

**Comment by shiyi0124** [comment]
Please send me a copy if you also can, thanks！ It would be of great help to me, too. My email at olivia000124@163.com

**Comment by passermyh** [comment]
Please send me a copy if you also can, thanks！ It would be of great help to me, too. My email at [1527299964@qq.com](mailto:1527299964@qq.com)

**Comment by Oddttfz** [comment]
Please send me a copy if you also can, thanks！ It would be of great help to me, too. My email at 2696857228@qq.com

**Comment by PengpengShao** [comment]
Please send me a copy if you also can, thanks！ It would be of great help to me, too. My email at [2696857228@qq.com](mailto:2411849793@qq.com)

**Comment by PengpengShao** [comment]
Please send me a copy if you also can, thanks！ It would be of great help to me, too. My email at [2411849793@qq.com]

**Comment by Jmkiy** [comment]
Please send me a copy if you can, thanks！ It would be of great help to me, too. My email at 2416787837@qq.com

**Comment by VinsonZhangS** [comment]
Please send me a copy if you also can, thanks！ It would be of great help to me, too. My email at sdzczs19980425@outlook.com

**Comment by VinsonZhangS** [comment]
您数据集发哪里了，我的邮箱里只收到了您关闭该issue的通知并没有收到您发的数据集相关内容？
