### ISSUE TITLE
Data set question about DB15K

### ISSUE THREAD

**Issue by dbbice** [HestiaSky/IMF-Pytorch#2]
Hi, first of all thank you very much for sharing your work. I experimented on FB15K and YAGO15K and achieved the same effect as the paper. But on DB15K, it has achieved extremely poor results. I don’t know if it’s the data set segmentation or something went wrong. Could you please upload your train, valid and test data sets? Thank you very much!

Looking forward to your reply~

**Comment by ilove0429jbx** [comment]
> 

HELLO,Could you please ask you some questions about the model? Here is my email j1131220481@163.com！Thank you！！！！！

**Comment by passermyh** [comment]
Hello, do you have the datasets and pickles the paper used? Here is my email [1527299964@qq.com](1527299964@qq.com)

**Comment by ilove0429jbx** [comment]
数据集在那个MMKG那个篇论文列你可以去搜一下，代码我准备这两天调试呢。&nbsp;


J1999
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月11日(星期二) 下午3:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HestiaSky/IMF-Pytorch] Data set question about DB15K (Issue #2)





 
Hello, do you have the datasets and pickles the paper used? Here is my email ***@***.***

**Comment by yunhui-Xu** [comment]
Hello, do you have the datasets and pickles the paper used? Here is my email [gela_su@126.com]

**Comment by zhiweihu1103** [comment]
I also cannot reproduce DB15K results, I only get MRR=44.5, Hits@1=38.0, Hits@3=47.5, Hits@10=57.1, I think the results is only close to IMF (w/o DF).

**Comment by ilove0429jbx** [comment]
可以加qq交流一下。qq：1131220481&nbsp;


J1999
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhiwei ***@***.***&gt;; 
发送时间: 2023年5月23日(星期二) 晚上9:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HestiaSky/IMF-Pytorch] Data set question about DB15K (Issue #2)





 
I also cannot reproduce DB15K results, I only get MRR=44.5, ***@***.***=38.0, ***@***.***=47.5, ***@***.***=57.1, I think the results is only close to IMF (w/o DF).

**Comment by Elbaz-k** [comment]
Hello, do you have the datasets and pickles the paper used? Here is my email [1071812398@qq.com]
