### ISSUE TITLE
How do I generate the ‘text_features.pkl’ file

### ISSUE THREAD

**Issue by aduaa** [HestiaSky/IMF-Pytorch#3]
Could you please tell me how the text_features.pkl file is generated

**Comment by xiaohetongxue** [comment]
您好，请问这个问题您解决了吗？我也遇到了这个问题。

**Comment by xiaohetongxue** [comment]
Have you solved this problem? I also ran into this problem, wondering how the text_featues.pkl file is generated?

**Comment by HestiaSky** [comment]
Hi, thanks for your interest.
text_features.pkl is generated by the pool output of BERT-base-uncased model of the text descriptions.
You can use the open-released model from huggingface and the text descriptions are contained in the 'dataset' folder.
