### ISSUE TITLE
I couldn't locate the img_features.pkl and text_features.pkl files.

### ISSUE THREAD

**Issue by wang991227** [HestiaSky/IMF-Pytorch#6]
This is a very interesting experiment！Could you please provide the img_features.pk and text_features.pkl files? Thank you!

**Comment by HestiaSky** [comment]
img_features can be directly obtained from MMKG. (https://github.com/mniepert/mmkb)
text_features is the pooled_output of entity descriptions of BERT_base_uncased.
Please see Section 2.2 for details.
