### ISSUE TITLE
I also couldn't locate the img_features.pkl and text_features.pkl files.

### ISSUE THREAD

**Issue by zhi520** [HestiaSky/IMF-Pytorch#7]
I also couldn't locate the img_features.pkl and text_features.pkl files.

**Comment by HestiaSky** [comment]
img_features can be directly obtained from MMKG. (https://github.com/mniepert/mmkb)
text_features is the pooled_output of entity descriptions of BERT_base_uncased.
Please see Section 2.2 for details.
